# # Definitions of tags to detect
#
# ## General remarksOS
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    #{id: 0, size: 0.032, name: },
    {id: 1, size: 0.032, name: F20_20_B},
    {id: 2, size: 0.032, name: F20_20_G},
    {id: 3, size: 0.032, name: S40_40_B},
    {id: 4, size: 0.032, name: S40_40_G},
    {id: 5, size: 0.032, name: M20_100},
    {id: 6, size: 0.032, name: M20},
    {id: 7, size: 0.032, name: M30},
    #{id: 8, size: 0.032, name: },
    #{id: 9, size: 0.032, name: },
    #{id: 10, size: 0.032, name: },
    #{id: 11, size: 0.032, name: },
    #{id: 12, size: 0.032, name: },
    #{id: 13, size: 0.032, name: },
    #{id: 14, size: 0.032, name: },
    #{id: 15, size: 0.032, name: },
    #{id: 16, size: 0.032, name: },
    #{id: 17, size: 0.032, name: },
    #{id: 18, size: 0.032, name: },
    {id: 19, size: 0.032, name: Axis2},
    {id: 20, size: 0.032, name: Bearing2},
    {id: 21, size: 0.032, name: Housing},
    {id: 22, size: 0.032, name: Motor2},
    {id: 23, size: 0.032, name: Spacer},
    {id: 24, size: 0.032, name: Screwdriver},
    {id: 25, size: 0.032, name: Wrench},
    {id: 26, size: 0.032, name: Drill},
    {id: 27, size: 0.032, name: AllenKey}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]